## Configuration, options depending on what your server wants to do with the chest ;)

# Potential player interactions
chest_interactions:
  # WARNING: WHEN A PLAYER BREAKS A CHEST
  # THE CHEST'S ITEMS WILL ONLY DROP IF THE OPTION BELOW IS TRUE
  player_breakable: false
  items_drop_when_broken: true
  # explosion_proof, true -> chest won't be destroyed if there's an explosion
  #                 false -> chest will be destroyed if there's an explosion
  # Items WILL disappear if option below isn't true
  explosion_proof: true
  items_drop_when_exploded: true

# Please tell me it's clear enough
chest_customization:
  name_on_chest: true

# Command-related stuff (WIP)
commands:
  # If you want for the command to be available for users ;)
  deathchest-list: true

# more options might be added later on, if you want an option...
# go to the Modrinth page and make a suggestion in the "Issues"
# maybe I'll make a better way to do

