name: DeathChest
version: '1.5.5'
main: me.pau.plugins.deathchest.DeathChest
api-version: '1.17'
author: defNotPau
description: Simple, hopefully efficient and reliable Death Chest plugin so items won't despawn

commands:
  deathchest:
    description: Main command for DeathChest plugin
    usage: /<command> [list]
    aliases: [dc]