name: DeathChest
version: '1.3'
main: me.pau.plugins.DeathChest
api-version: '1.20'
author: defNotPau
description: Simple, hopefully efficient and reliable deathchest plugin so items won't really despawn
commands:
  coords:
    usage: /coords
    description: Logs the player's coordinates.
    permission: deathchest.coords
    aliases: [latest]